//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class arcStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal arcStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Formats.Strings.arcStrings", typeof(arcStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Archive contents might be encrypted,
        ///choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string AGSMightBeEncrypted {
            get {
                return ResourceManager.GetString("AGSMightBeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base archive 的本地化字符串。
        /// </summary>
        public static string AMIBaseArchive {
            get {
                return ResourceManager.GetString("AMIBaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New archive will also contain entries from the base archive. 的本地化字符串。
        /// </summary>
        public static string AMIBaseTooltip {
            get {
                return ResourceManager.GetString("AMIBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select base archive 的本地化字符串。
        /// </summary>
        public static string AMIChooseBase {
            get {
                return ResourceManager.GetString("AMIChooseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amaterasu Translations Muv-Luv archive 的本地化字符串。
        /// </summary>
        public static string AMIDescription {
            get {
                return ResourceManager.GetString("AMIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No files suitable for AMI archive found. 的本地化字符串。
        /// </summary>
        public static string AMINoFiles {
            get {
                return ResourceManager.GetString("AMINoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string ArcDefault {
            get {
                return ResourceManager.GetString("ArcDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive content is encrypted.
        ///Choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string ArcEncryptedNotice {
            get {
                return ResourceManager.GetString("ArcEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32-bit hex number 的本地化字符串。
        /// </summary>
        public static string ArcHex32Bit {
            get {
                return ResourceManager.GetString("ArcHex32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore encryption 的本地化字符串。
        /// </summary>
        public static string ArcIgnoreEncryption {
            get {
                return ResourceManager.GetString("ArcIgnoreEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image is encrypted. 的本地化字符串。
        /// </summary>
        public static string ArcImageEncrypted {
            get {
                return ResourceManager.GetString("ArcImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no encryption 的本地化字符串。
        /// </summary>
        public static string ArcNoEncryption {
            get {
                return ResourceManager.GetString("ArcNoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ArcReset {
            get {
                return ResourceManager.GetString("ArcReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose title or enter a password 的本地化字符串。
        /// </summary>
        public static string ArcTitleOrPassword {
            get {
                return ResourceManager.GetString("ArcTitleOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default file names encoding 的本地化字符串。
        /// </summary>
        public static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption keys 的本地化字符串。
        /// </summary>
        public static string DPKKeys {
            get {
                return ResourceManager.GetString("DPKKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase. 的本地化字符串。
        /// </summary>
        public static string FJSYSNotice {
            get {
                return ResourceManager.GetString("FJSYSNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose title or enter a key 的本地化字符串。
        /// </summary>
        public static string GALChoose {
            get {
                return ResourceManager.GetString("GALChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 âge proprietary image format 的本地化字符串。
        /// </summary>
        public static string GRPDescription {
            get {
                return ResourceManager.GetString("GRPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liar-soft proprietary script format 的本地化字符串。
        /// </summary>
        public static string GSCDescription {
            get {
                return ResourceManager.GetString("GSCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image is encrypted.
        ///Choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string GYUImageEncrypted {
            get {
                return ResourceManager.GetString("GYUImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose game executable file 的本地化字符串。
        /// </summary>
        public static string INTChooseExe {
            get {
                return ResourceManager.GetString("INTChooseExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypted archives creation is not implemented. 的本地化字符串。
        /// </summary>
        public static string INTCreationNotice {
            get {
                return ResourceManager.GetString("INTCreationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CatSystem2 engine resource archive 的本地化字符串。
        /// </summary>
        public static string INTDescription {
            get {
                return ResourceManager.GetString("INTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check EXE 的本地化字符串。
        /// </summary>
        public static string INTExeButton {
            get {
                return ResourceManager.GetString("INTExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable Files 的本地化字符串。
        /// </summary>
        public static string INTExeFiles {
            get {
                return ResourceManager.GetString("INTExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key not found within {0}. 的本地化字符串。
        /// </summary>
        public static string INTKeyNotFound {
            get {
                return ResourceManager.GetString("INTKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric key should be a 32-bit hexadecimal integer 的本地化字符串。
        /// </summary>
        public static string INTKeyRequirement {
            get {
                return ResourceManager.GetString("INTKeyRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric key 的本地化字符串。
        /// </summary>
        public static string INTLabelNumericKey {
            get {
                return ResourceManager.GetString("INTLabelNumericKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press &quot;Check EXE&quot; button to look for key within game executable file. 的本地化字符串。
        /// </summary>
        public static string INTMessage1 {
            get {
                return ResourceManager.GetString("INTMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternatively, enter archive encryption key or choose one of the predefined encryption schemes. 的本地化字符串。
        /// </summary>
        public static string INTMessage2 {
            get {
                return ResourceManager.GetString("INTMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive directory is encrypted. 的本地化字符串。
        /// </summary>
        public static string INTNotice {
            get {
                return ResourceManager.GetString("INTNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string KCAPDefault {
            get {
                return ResourceManager.GetString("KCAPDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kogado game engine resource archive 的本地化字符串。
        /// </summary>
        public static string KogadoDescription {
            get {
                return ResourceManager.GetString("KogadoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption scheme 的本地化字符串。
        /// </summary>
        public static string LabelEncScheme {
            get {
                return ResourceManager.GetString("LabelEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passphrase 的本地化字符串。
        /// </summary>
        public static string LabelPassphrase {
            get {
                return ResourceManager.GetString("LabelPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheme 的本地化字符串。
        /// </summary>
        public static string LabelScheme {
            get {
                return ResourceManager.GetString("LabelScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liar-soft image archive 的本地化字符串。
        /// </summary>
        public static string LWGDescription {
            get {
                return ResourceManager.GetString("LWGDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase. 的本地化字符串。
        /// </summary>
        public static string MBLNotice {
            get {
                return ResourceManager.GetString("MBLNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive content is encrypted. 的本地化字符串。
        /// </summary>
        public static string MCAEncryptedNotice {
            get {
                return ResourceManager.GetString("MCAEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose title or enter a key 的本地化字符串。
        /// </summary>
        public static string MCGChoose {
            get {
                return ResourceManager.GetString("MCGChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8-bit encryption key 的本地化字符串。
        /// </summary>
        public static string MCGLabelKey {
            get {
                return ResourceManager.GetString("MCGLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding file 的本地化字符串。
        /// </summary>
        public static string MsgAddingFile {
            get {
                return ResourceManager.GetString("MsgAddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculating checksum... 的本地化字符串。
        /// </summary>
        public static string MsgCalculatingChecksum {
            get {
                return ResourceManager.GetString("MsgCalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing index... 的本地化字符串。
        /// </summary>
        public static string MsgCompressingIndex {
            get {
                return ResourceManager.GetString("MsgCompressingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption key required for archive creation. 的本地化字符串。
        /// </summary>
        public static string MsgCreationKeyRequired {
            get {
                return ResourceManager.GetString("MsgCreationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption method not implemented 的本地化字符串。
        /// </summary>
        public static string MsgEncNotImplemented {
            get {
                return ResourceManager.GetString("MsgEncNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name extension too long. 的本地化字符串。
        /// </summary>
        public static string MsgExtensionTooLong {
            get {
                return ResourceManager.GetString("MsgExtensionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name is too long 的本地化字符串。
        /// </summary>
        public static string MsgFileNameTooLong {
            get {
                return ResourceManager.GetString("MsgFileNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name contains illegal characters 的本地化字符串。
        /// </summary>
        public static string MsgIllegalCharacters {
            get {
                return ResourceManager.GetString("MsgIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: image format not recognized. 的本地化字符串。
        /// </summary>
        public static string MsgInvalidImageFormat {
            get {
                return ResourceManager.GetString("MsgInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid archive version specified. 的本地化字符串。
        /// </summary>
        public static string MsgInvalidVersion {
            get {
                return ResourceManager.GetString("MsgInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name without extension. 的本地化字符串。
        /// </summary>
        public static string MsgNoExtension {
            get {
                return ResourceManager.GetString("MsgNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of files exceedes archive limit. 的本地化字符串。
        /// </summary>
        public static string MsgTooManyFiles {
            get {
                return ResourceManager.GetString("MsgTooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating index... 的本地化字符串。
        /// </summary>
        public static string MsgUpdatingIndex {
            get {
                return ResourceManager.GetString("MsgUpdatingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing index... 的本地化字符串。
        /// </summary>
        public static string MsgWritingIndex {
            get {
                return ResourceManager.GetString("MsgWritingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress contents 的本地化字符串。
        /// </summary>
        public static string NPACompressContents {
            get {
                return ResourceManager.GetString("NPACompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nitro+ resource archive 的本地化字符串。
        /// </summary>
        public static string NPADescription {
            get {
                return ResourceManager.GetString("NPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption keys
        ///(required even if contents is not encrypted) 的本地化字符串。
        /// </summary>
        public static string NPAKeys {
            get {
                return ResourceManager.GetString("NPAKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nitro+ Steins;Gate resource archive 的本地化字符串。
        /// </summary>
        public static string NPASteinsGateDescription {
            get {
                return ResourceManager.GetString("NPASteinsGateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NScripter game engine resource archive 的本地化字符串。
        /// </summary>
        public static string NSADescription {
            get {
                return ResourceManager.GetString("NSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default audio sampling rate 的本地化字符串。
        /// </summary>
        public static string ODNAudioSampleRate {
            get {
                return ResourceManager.GetString("ODNAudioSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix Ogg files checksums 的本地化字符串。
        /// </summary>
        public static string OGGFixCrc {
            get {
                return ResourceManager.GetString("OGGFixCrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive type 的本地化字符串。
        /// </summary>
        public static string ONSArchiveType {
            get {
                return ResourceManager.GetString("ONSArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression 的本地化字符串。
        /// </summary>
        public static string ONSCompression {
            get {
                return ResourceManager.GetString("ONSCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string ONSCompressionNone {
            get {
                return ResourceManager.GetString("ONSCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flying Shine resource archive 的本地化字符串。
        /// </summary>
        public static string PDDescription {
            get {
                return ResourceManager.GetString("PDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scramble contents 的本地化字符串。
        /// </summary>
        public static string PDScrambleContents {
            get {
                return ResourceManager.GetString("PDScrambleContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use default encryption scheme 的本地化字符串。
        /// </summary>
        public static string QLIEDefaultScheme {
            get {
                return ResourceManager.GetString("QLIEDefaultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load transparency data from RC8 bitmap 的本地化字符串。
        /// </summary>
        public static string RCTApplyMask {
            get {
                return ResourceManager.GetString("RCTApplyMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically combine incremental frames 的本地化字符串。
        /// </summary>
        public static string RCTOverlayFrames {
            get {
                return ResourceManager.GetString("RCTOverlayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ren&apos;Py game engine archive 的本地化字符串。
        /// </summary>
        public static string RPADescription {
            get {
                return ResourceManager.GetString("RPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32-bit key 的本地化字符串。
        /// </summary>
        public static string RPALabelKey {
            get {
                return ResourceManager.GetString("RPALabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File resembles RPM resource archive,
        ///but encryption key guess failed.
        ///Choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string RPMEncryptedNotice {
            get {
                return ResourceManager.GetString("RPMEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amaterasu Translations Muv-Luv script file 的本地化字符串。
        /// </summary>
        public static string SCRDescription {
            get {
                return ResourceManager.GetString("SCRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename encoding 的本地化字符串。
        /// </summary>
        public static string SGLabelEncoding {
            get {
                return ResourceManager.GetString("SGLabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Tim2 image alpha format.
        ///It can&apos;t be read correctly from the file. 的本地化字符串。
        /// </summary>
        public static string Tim2AlphaFormat {
            get {
                return ResourceManager.GetString("Tim2AlphaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex number 的本地化字符串。
        /// </summary>
        public static string TooltipHex {
            get {
                return ResourceManager.GetString("TooltipHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum file name length
        ///(not including extension) 的本地化字符串。
        /// </summary>
        public static string WARCLabelLength {
            get {
                return ResourceManager.GetString("WARCLabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liar-soft game resource archive 的本地化字符串。
        /// </summary>
        public static string XFLDescription {
            get {
                return ResourceManager.GetString("XFLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress contents 的本地化字符串。
        /// </summary>
        public static string XP3CompressContents {
            get {
                return ResourceManager.GetString("XP3CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress directory 的本地化字符串。
        /// </summary>
        public static string XP3CompressHeader {
            get {
                return ResourceManager.GetString("XP3CompressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KiriKiri game engine resource archive 的本地化字符串。
        /// </summary>
        public static string XP3Description {
            get {
                return ResourceManager.GetString("XP3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive content could be encrypted.
        ///Choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string XP3EncryptedNotice {
            get {
                return ResourceManager.GetString("XP3EncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string XP3LabelVersion {
            get {
                return ResourceManager.GetString("XP3LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retain directory structure 的本地化字符串。
        /// </summary>
        public static string XP3RetainStructure {
            get {
                return ResourceManager.GetString("XP3RetainStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yu-Ris game engine resource archive 的本地化字符串。
        /// </summary>
        public static string YPFDescription {
            get {
                return ResourceManager.GetString("YPFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8-bit encryption key 的本地化字符串。
        /// </summary>
        public static string YPFLabelKey {
            get {
                return ResourceManager.GetString("YPFLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive version 的本地化字符串。
        /// </summary>
        public static string YPFLabelVersion {
            get {
                return ResourceManager.GetString("YPFLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive directory is encrypted.
        ///Choose appropriate encryption scheme. 的本地化字符串。
        /// </summary>
        public static string YPFNotice {
            get {
                return ResourceManager.GetString("YPFNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to guess 的本地化字符串。
        /// </summary>
        public static string YPFTryGuess {
            get {
                return ResourceManager.GetString("YPFTryGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive content is encrypted. 的本地化字符串。
        /// </summary>
        public static string ZIPEncryptedNotice {
            get {
                return ResourceManager.GetString("ZIPEncryptedNotice", resourceCulture);
            }
        }
    }
}
