//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class garStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal garStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Strings.garStrings", typeof(garStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enables various extensions, such as transparency support. 的本地化字符串。
        /// </summary>
        public static string BMPExtensionsDesc {
            get {
                return ResourceManager.GetString("BMPExtensionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable BMP format extensions 的本地化字符串。
        /// </summary>
        public static string BMPExtensionsText {
            get {
                return ResourceManager.GetString("BMPExtensionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPEG compression quality 的本地化字符串。
        /// </summary>
        public static string JPEGQualityText {
            get {
                return ResourceManager.GetString("JPEGQualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File is empty 的本地化字符串。
        /// </summary>
        public static string MsgFileIsEmpty {
            get {
                return ResourceManager.GetString("MsgFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File is too large 的本地化字符串。
        /// </summary>
        public static string MsgFileTooLarge {
            get {
                return ResourceManager.GetString("MsgFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inappropriate encryption scheme 的本地化字符串。
        /// </summary>
        public static string MsgInvalidEncryption {
            get {
                return ResourceManager.GetString("MsgInvalidEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file name 的本地化字符串。
        /// </summary>
        public static string MsgInvalidFileName {
            get {
                return ResourceManager.GetString("MsgInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file format 的本地化字符串。
        /// </summary>
        public static string MsgInvalidFormat {
            get {
                return ResourceManager.GetString("MsgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown encryption scheme 的本地化字符串。
        /// </summary>
        public static string MsgUnknownEncryption {
            get {
                return ResourceManager.GetString("MsgUnknownEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 file could not be opened as resource archive 的本地化字符串。
        /// </summary>
        public static string MsgUnknownFormat {
            get {
                return ResourceManager.GetString("MsgUnknownFormat", resourceCulture);
            }
        }
    }
}
